# Generated by Django 3.0.1 on 2019-12-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='Surname', max_length=50),
        ),
    ]
