# Generated by Django 3.0.1 on 2019-12-24 18:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50000000), django.core.validators.MinValueValidator(1)])),
                ('productionYear', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1900)])),
                ('color', models.CharField(max_length=20)),
                ('kilometers', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000000), django.core.validators.MinValueValidator(1)])),
                ('kW', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7000), django.core.validators.MinValueValidator(1)])),
                ('cm3', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('image', models.CharField(max_length=1000)),
                ('contactNumber', models.CharField(max_length=15)),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('adOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
