# Generated by Django 3.0.1 on 2019-12-24 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cm3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='kW',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='kilometers',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
