# Generated by Django 3.0.1 on 2019-12-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191224_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='car_pics'),
        ),
    ]
